trigger:
  branches:
    include:
    - main

pr:
  branches:
    include:
    - "*"

stages:
- stage: Plan
  displayName: Plan
  jobs:
  - job: Plan
    displayName: Terraform plan
    pool:
      name: default
    steps:
    - template: pipelines/templates/terraform-plan.yml
      parameters:
        azureServiceConnection: SC-AZURE
        workingDirectory: terraform/envs/dev
        tfVersion: 1.6.6

- stage: Apply
  displayName: Apply
  dependsOn: Plan
  condition: and(succeeded(), eq(variables['Build.SourceBranch'], 'refs/heads/main'))
  jobs:
  - deployment: ApplyDev
    displayName: Terraform apply (dev)
    environment: cvm-dev
    pool:
      name: default
    strategy:
      runOnce:
        deploy:
          steps:
          - template: pipelines/templates/terraform-apply.yml
            parameters:
              azureServiceConnection: SC-AZURE
              workingDirectory: terraform/envs/dev
              tfVersion: 1.6.6
